"use client";
import { useMemo, useState } from "react";
import type { Student } from "../lib/reservadesk-demo";
import { limits, seatZone, students, zones } from "../lib/reservadesk-demo";

export function ReservaDeskDemo() {
  const [email, setEmail] = useState("fam001-1@reservadesk.demo");
  const [student, setStudent] = useState<Student | null>(null);
  const [selected, setSelected] = useState<number[]>([]);
  const [paid, setPaid] = useState(false);
  const [notice, setNotice] = useState("");
  const locked = useMemo(() => new Set([3,4,7,8,21,22,34,35,63,64,80,81,121,122,145,146]), []);
  const siblings = student ? students.filter((item) => item.family === student.family && item.id !== student.id) : [];
  const limit = student ? limits[student.functionNo as 1 | 2 | 3] : 0;
  const total = selected.reduce((sum, seat) => sum + seatZone(seat).price, 0);
  function login(event: React.FormEvent) { event.preventDefault(); const match = students.find((item) => item.email === email.toLowerCase()); if (!match) { setNotice("Cuenta no encontrada. Usa una de las cuentas demo indicadas."); return; } setStudent(match); setNotice(""); }
  function toggle(seat: number) { if (!student || locked.has(seat) || paid) return; if (selected.includes(seat)) return setSelected(selected.filter((item) => item !== seat)); if (selected.length >= limit) return setNotice(`Tu familia ya alcanzó el límite de ${limit} boletos para esta función.`); setNotice(""); setSelected([...selected, seat]); }
  async function pay() { if (!student || selected.length === 0) return setNotice("Selecciona al menos un asiento."); setPaid(true); setNotice("Pago Demo acreditado. Tu recibo está listo."); const response = await fetch("/api/reservadesk/receipt", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({ student: student.name, email: student.email, family: student.family, functionNo: student.functionNo, seats:selected, total }) }); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href=url; link.download="recibo-reservadesk.pdf"; link.click(); URL.revokeObjectURL(url); }
  if (!student) return <section className="rd-login"><div className="rd-brand"><span>RESERVA</span><strong>DESK</strong><small>Festival Educativo 2026</small></div><form onSubmit={login} className="rd-login-card"><p className="eyebrow">Acceso de alumno</p><h1>Tu lugar comienza aquí.</h1><p>Ingresa con una cuenta demo para reservar boletos de tu función.</p><label>Correo demo<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" /></label><label>Contraseña<input defaultValue="Festival2026!" type="password" /></label>{notice && <p className="rd-alert">{notice}</p>}<button>Iniciar sesión <span>→</span></button><small>Ejemplo: fam001-1@reservadesk.demo · Festival2026!</small></form></section>;
  return <section className="rd-app"><header className="rd-header"><div className="rd-brand"><span>RESERVA</span><strong>DESK</strong></div><div><b>{student.name}</b><small>{student.family} · Nivel {student.level}</small></div></header><div className="rd-layout"><aside className="rd-sidebar"><p className="eyebrow">Mi perfil</p><h2>{student.name}</h2><p className="rd-muted">Nivel {student.level} · Función {student.functionNo}</p><div className="rd-family"><strong>Familia {student.family}</strong><span>{student.parents.join(" y ")}</span><small>Hermanos: {siblings.length ? siblings.map((item) => `${item.name} (N${item.level})`).join(", ") : "Sin hermanos registrados"}</small></div><div className="rd-limit"><span>Boletos familiares disponibles</span><strong>{limit - selected.length} <small>/ {limit}</small></strong><i><b style={{ width:`${(selected.length / limit) * 100}%` }} /></i></div><div className="rd-zones"><p className="eyebrow">Zonas</p>{zones.map((zone) => <div key={zone.name}><span className={`zone-dot ${zone.name.toLowerCase()}`} />{zone.name}<b>${zone.price}</b></div>)}</div></aside><main className="rd-main"><div className="rd-function"><div><p className="eyebrow">Festival educativo</p><h1>Función {student.functionNo} · {student.functionNo === 1 ? "Descubre" : student.functionNo === 2 ? "Imagina" : "Crea"}</h1><p>24 de octubre · {student.functionNo === 1 ? "10:00" : student.functionNo === 2 ? "13:30" : "17:00"} h</p></div><div className="rd-hold">Apartado temporal<br /><b>10:00</b></div></div><div className="rd-stage">ESCENARIO</div><div className="rd-legend"><span><i className="available" />Disponible</span><span><i className="held" />Apartado</span><span><i className="selected" />Tu selección</span><span><i className="occupied" />Ocupado</span></div><div className="rd-seat-map">{Array.from({ length:180 }, (_,index) => { const seat=index+1; const zone=seatZone(seat); const isSelected=selected.includes(seat); const isLocked=locked.has(seat); return <button aria-label={`Asiento ${seat}, zona ${zone.name}`} onClick={() => toggle(seat)} key={seat} className={`rd-seat ${zone.name.toLowerCase()} ${isSelected ? "is-selected" : ""} ${isLocked ? "is-locked" : ""}`}>{seat}</button>; })}</div><div className="rd-checkout"><div><span>{selected.length} asiento{selected.length === 1 ? "" : "s"} seleccionado{selected.length === 1 ? "" : "s"}</span><strong>${total.toLocaleString("es-MX")} MXN</strong></div><button onClick={pay} disabled={paid}>{paid ? "Compra acreditada" : "Pagar en modo Demo →"}</button></div>{notice && <p className="rd-alert">{notice}</p>}</main></div></section>;
}
